---
- name: Gather Facts
  gather_facts: True
  hosts: eve_devices
  
  tasks:
  - ios_config:
      backup: yes
  - ios_facts:
      gather_subset: "!config"
    register: ios_facts_out 
  - copy: content="{{ ios_facts_out | to_nice_json }}" dest="backup/{{ ansible_host }}.json"
