---
- name: Save Configurations (IOS)
  connection: local
  gather_facts: False
  hosts: routers 
  vars_files:
    - /etc/ansible/cred.yml
  
  tasks:
  - name: Configure Provider
    set_fact:
      provider:
        username: "{{ username }}"
        password: "{{ password }}"
        host: "{{ inventory_hostname }}"

  - name: Test reachability to 8.8.8.8 using default vrf
    ios_ping:
      dest: 8.8.8.8
  - name: Backup Config
    ios_config:
      backup: yes
  - name: check the running-config against master config
    ios_config:
      diff_against: intended
      intended_config: "{{ lookup('file', 'master.cfg') }}"
      provider: "{{ provider }}"
