---
- name: Save Configurations (IOS)
  gather_facts: True
  hosts: lab_devices 
  
  tasks:
  - name: Test reachability to 10.213.100.1 using default vrf
    ios_ping:
      dest: 10.213.100.1
  - name: Backup Config
    ios_config:
      backup: yes
  - name: check the running-config against master config
    ios_config:
      diff_against: intended
      intended_config: "{{ lookup('file', 'master.cfg') }}"
  - name: apply new lines
    ios_config:
      parents: line con 0
      commands:
        - exec-timeout 10 0
        - exec-banner
      match: exact
      replace: block
      before:
        - line con 0
        - no exec-timeout
      after:
        - line con 0
      save_when: modified
  - name: Push Config
    ios_config:
      src: /etc/ansible/playbooks/test.cfg
