---
- name: Save Configurations (IOS)
  gather_facts: True
  hosts: routers 
  
  tasks:
  - name: Test reachability to 10.213.100.1 using default vrf
    ios_ping:
      dest: 10.213.100.1
  - name: Backup Config
    ios_config:
      backup: yes
  - name: check the running-config against master config
    ios_config:
      diff_against: intended
      intended_config: "{{ lookup('file', 'master.cfg') }}"
